babaseurl = "http://littleeh.com"
author = "Andrea Sweny"
title = "running mind"
logo = "/nugget_point.jpg"
enableEmoji = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
theme = "basics"
sectionPagesMenu = "main"
buildDrafts = false

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.R$"]

[permalinks]
  post = "/:year/:month/:day/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about/"

[params]
  logo = "/nugget_point.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
  author = "andrea sweny"